### ISSUE TITLE
Support for clusterssh

### ISSUE THREAD

**Issue by pdellaert** [wagoodman/bridgy#24]
**Feature Request**
Ability to use/enable [clusterssh](https://github.com/duncs/clusterssh) when SSH'ing to multiple servers so you can run the same command on all servers at once.

**Comment by wagoodman** [comment]
I haven't used clusterssh personally, but the same thing (or something very similar) can be achieved by running bridgy in tmux mode (either `--tmux` on the cli or add the persistent config option) to connect to multiple systems at once and then synchronizing input in tmux to all panes via `:setw synchronize-panes` (see https://sanctum.geek.nz/arabesque/sync-tmux-panes/).

Let me know if you want more info or if I misunderstood what you're really looking for.

**Comment by pdellaert** [comment]
That is indeed what i am looking for, just think it would be nice to have it as an extra option instead of having to configure manually after running bridgy in tmux mode. Not a big priority, just a nice to have.

**Comment by wagoodman** [comment]
Not a bad idea, but since the feature is already implemented via tmux then I won't plan to incorporate this unless there is more traction with other users. Thanks, though!
