### ISSUE TITLE
Provide option to search instance within ONE source

### ISSUE THREAD

**Issue by qinfeng** [wagoodman/bridgy#25]
I have multiple servers within multiple AWS account therefore I will have multiple AWS source for servers.

It will be much faster and better if there is an option to narrow down instance searching within ONE source.

**Comment by wagoodman** [comment]
Added the option `-i source-name` / `--source source-name` that allows you to provide one or more sources (via csv param). This will narrow down all sources searched to only the provided names (matched in the bridgy config).

fixed in c36ad45aba564ec16795b18932ffb48f0e77912a
