### ISSUE TITLE
Updating AWS inventory doesn't show changes to instances

### ISSUE THREAD

**Issue by bootswithdefer** [wagoodman/bridgy#26]
When you change the Name tag (or and instance gets a new IP, etc) of an AWS instance and run bridgy update, subsequent commands do not see the updated information.  Removing the cache files in ~/.bridgy/inventory/aws/profile/* and running an update causes the correct information to be used.

**Comment by wagoodman** [comment]
Fixed by e07f90937f6750d096cb5c8bfbcbd1a8d4407480
